spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}  # Gmail 계정
    password: ${MAIL_PASSWORD}  # Gmail 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Redis
  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# S3
cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
      path:
        pet: pet
        walk: walk
        review: review
        community: community
        dday: dday
        profile: profile


    region:
      static: ${CLOUD_AWS_REGION_STATIC}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
